### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by injainja** [IMC-GER/phpBB-Image-upload-use-ImageMagick#1]
Fatal error: Uncaught Error: Call to undefined function imcger\curlyquotes\event\str_contains() in /pages/51/66/d0015911/home/htdocs/heilforum.de/ext/imcger/curlyquotes/event/main_listener.php:96 Stack trace: #0 /pages/51/66/d0015911/home/htdocs/heilforum.de/ext/imcger/curlyquotes/event/main_listener.php(51): imcger\curlyquotes\event\main_listener->get_browser_lang('de') #1 /pages/51/66/d0015911/home/htdocs/heilforum.de/cache/production/container_4335734bbdd20f586549a504dff5f80c.php(3783): imcger\curlyquotes\event\main_listener->__construct(Object(phpbb\user), Object(phpbb\request\request), Object(imcger\curlyquotes\core\fixer)) #2 /pages/51/66/d0015911/home/htdocs/heilforum.de/cache/production/container_4335734bbdd20f586549a504dff5f80c.php(3009): phpbb_cache_container->getImcger_Curlyquotes_ListenerService() #3 /pages/51/66/d0015911/home/htdocs/heilforum.de/vendor/symfony/event-dispatcher/EventDispatcher.php(231): phpbb_cache_container->{closure}() #4 /pages/51/66/d0015911/home/htdocs/heilforum.de/vendor/symfony/event-di in /pages/51/66/d0015911/home/htdocs/heilforum.de/ext/imcger/curlyquotes/event/main_listener.php on line 96

**Comment by IMC-GER** [comment]
Hi, the phpBB extension  imcger\curlyquotes needs php 8.0 or higher.
